### PR TITLE
add style2.cc and modify index.html

### PR DESCRIPTION
**Pull request by PKmaina**
created for additional desing to the index.html

### CODE REVIEW

**Comment by chriswachira** [comment]
Nice work, mate!

**Comment by gr1d99** [comment]
awesome use of external libraries, great work.

**Comment by gr1d99** [comment]
and check on the conflicts.

**Comment by PKmaina** [comment]
Thank you for your feedback guys, appreciate it.

**Comment by PKmaina** [comment]
Hi Gideon could you help me out and explain more on your last point

**Comment by gr1d99** [comment]
just above the comment box there is a small thumbnail that shows there are two files conflicting. you should see it since its in your repo, if you don't see it let me know so that I can take a screenshot

**Comment by PKmaina** [comment]
I am kinda having a hard time finding, could kindly send me the screenshot

**Pull request merged**
